project:
  type: website

website:
  title: stadt-geschichte-basel.github.io
  favicon: android-chrome-512x512.png
  open-graph: true
  twitter-card: true
  site-url: https://Stadt-Geschichte-Basel.github.io/stadt-geschichte-basel.github.io/
  repo-url: https://github.com/Stadt-Geschichte-Basel/stadt-geschichte-basel.github.io/
  issue-url: https://github.com/Stadt-Geschichte-Basel/stadt-geschichte-basel.github.io/issues/new/choose
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  back-to-top-navigation: true
  search:
    show-item-context: true
    type: overlay
  navbar:
    logo: android-chrome-512x512.png
    logo-alt: ''
    title: Stadt.Geschichte.Basel
    tools:
      - icon: github
        url: https://github.com/Stadt-Geschichte-Basel/stadt-geschichte-basel.github.io/
    left:
      - text: Home
        href: index.qmd
      - text: Produkte
        href: products/index.qmd

  sidebar:
    contents:
      - text: Home
        href: index.qmd
      - section: Produkte
        href: products/index.qmd
        contents: products/*/index.qmd

format:
  html:
    toc: true
    theme: cosmo
    code-copy: true
    code-overflow: wrap
    css: styles.css

freeze: true

editor: visual
