contact_links:
  - name: Are you looking for documentation on stadt-geschichte-basel.github.io?
    url: https://Stadt-Geschichte-Basel.github.io/stadt-geschichte-basel.github.io
    about: Please see the documentation for stadt-geschichte-basel.github.io on its GitHub Pages page.
  - name: Do want to discuss stadt-geschichte-basel.github.io with the community?
    url: https://github.com/Stadt-Geschichte-Basel/stadt-geschichte-basel.github.io/discussions
    about: Please see the discussions page for stadt-geschichte-basel.github.io.
blank_issues_enabled: true
