---
title: "Forschungsdatenmanagement und Public History"
lang: de
listing:
  - id: presentations
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "Vortrag"
  - id: posters
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "Poster"
  - id: workshops
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "Workshop"
  - id: panels
    type: table
    categories: false
    contents:
      - talks-posters/*/index.qmd
    sort: "date desc"
    sort-ui: false
    filter-ui: false
    fields: [date, title, event]
    field-display-names: 
      title: 'Titel'
      event: 'Veranstaltung'
    include:
      categories: "{Panel,Roundtable}*"
  - id: coding
    type: grid
    contents: coding/*/index.qmd
    sort: "title"
    fields: [title, subtitle]
    grid-columns: 2
  - id: digital-history
    type: grid
    categories: false
    contents: digital-history/*/index.qmd
    fields: [title]
  - id: interna
    type: grid
    grid-columns: 2
    categories: true
    contents: interna/*/index.qmd
    fields: [title]
  - id: publications
    type: grid
    categories: false
    contents: publications/*/index.qmd
    fields: [title, subtitle]
    include:
      categories: "Publikation"
  - id: datastories
    type: grid
    categories: false
    contents: publications/*/index.qmd
    fields: [title, subtitle]
    include:
      categories: "Data Story"
  - id: research-data
    type: grid
    contents: [research-data/*/index.qmd]
    fields: [title]
    grid-columns: 2
date-modified: last-modified
---

::: {#frontrow}
:::

## Publikationen

::: {#publications}
:::

### Data Stories

::: {#datastories}
:::

## Coding

::: {#coding}
:::

## Forschungsdaten

::: {#research-data}
:::

## Vorträge, Poster und Workshops

Wissenschaftliche Veröffentlichungen, die im Zusammenhang mit dem Forschungsprojekt stehen, sind [auf Zenodo archiviert](https://zenodo.org/communities/stadt-geschichte-basel). Die im Rahmen von Konferenzen und Workshops publizierten Beiträge des Teams für Forschungsdatenmanagement und Public History befassen sich mit der Entwicklung der digitalen Angebote von Stadt.Geschichte.Basel und übergreifend mit (digitalem) Forschungsdatenmanagement und Public History in den Geschichtswissenschaften. Erfasst sind [Vorträge](#vorträge), die Organisation von bzw. Teilnahme an [Panels/Roundtables](#panels-und-roundtables), veranstaltete [Workshops](#workshops) sowie wissenschaftliche [Posterpräsentationen](#poster).

### Vorträge {#vorträge}

::: {#presentations}
:::

### Panels und Roundtables {#panels-und-roundtables}

::: {#panels}
:::

### Workshops {#workshops}

<div>

</div>

### Poster {#poster}

::: {#posters}
:::

## Community Building

::: {#digital-history}
:::

## Interna

::: {#interna}
:::